pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - status-success=Tests / test (12.x) (push) 
      - status-success=Tests / test (13.12.x) (push) 
      - status-success=Lint / test (13.12.x) (push) 
      - author=jorge07
    actions:
      merge:
        method: merge
